### ISSUE TITLE
Question: Планируется ли PR в основной репозиторий проекта CodeMirror?

### ISSUE THREAD

**Issue by sfaqer** [sikuda/codemirror-1C#2]
Есть ли в планах влить изменения в части хайлайта 1С в реп: https://github.com/codemirror/codemirror ?

**Comment by sikuda** [comment]
Ну честно говоря не задумывался, да и технически не знаю как сделать. Лицензия у меня та-же что у них и вообще все было написано на аналогии с basic ;)
Просветите что для этого надо сделать? Тогда надо делать fork и добавляя свои файлы предложить им  pullrequest? А то все как-то на коленке получилось.

**Comment by sfaqer** [comment]
Да, необходимо форкнуть основной проект, внести свои изменения, и сделать пул реквест к ним в репо. Есть гайдлайн для контрибьюторов у них же в репо: https://github.com/codemirror/CodeMirror/blob/master/CONTRIBUTING.md#contributing-code

**Comment by sikuda** [comment]
Спасибо за помощь. Держим кулачки - https://github.com/codemirror/CodeMirror/pull/5855

**Comment by sfaqer** [comment]
Отлично!)
Что-то правда блид на CI развалился, npm test вернул 1, хотя информации о том какой тест упал почему-то в логах нет: https://travis-ci.org/codemirror/CodeMirror/jobs/521841496
Есть возможность локально запустить тесты? Может скажет что нибудь более осмысленное.

**Comment by sikuda** [comment]
На  самом деле все плохо. У них 6 версия в дистрибутиве и другая архитектура. Предложили костыль elixir mode. Думаешь надо?

**Comment by sikuda** [comment]
К сожалению они вовсю заниматся 6 версией, а там другая архитектура

**Comment by sikuda** [comment]
К сожалению они вовсю занимаются 6 версией, а там другая архитектура
