### ISSUE TITLE
Есть ли возможность отдельно раскрасить код языка запросов ?

### ISSUE THREAD

**Issue by milanse** [sikuda/codemirror-1C#3]

**Comment by sikuda** [comment]
Тогда уточняющий вопрос: Интересует отдельная подсветка языка запросов в отдельном окне (есть в 1С) или подсветка в тексте кода(нет в 1С)?

**Comment by milanse** [comment]
Да, хотел прикрутить к консоли запросов, в принципе внутри видно как можно поправить, но хотелось бы, конечно, рулить отдельным флажком видом текста. 

Но сейчас вижу, что еще и мышка не работает пока, пичалька.

**Comment by sikuda** [comment]
Нет, пока разработки для языка запросов нет.
