### ISSUE TITLE
TYPORA markdown редактор

### ISSUE THREAD

**Issue by kirill-1000** [sikuda/codemirror-1C#5]
Вы не пробовали прикрутит вашу разметку к этому редактору? Он использует codemirror в качестве разметки подсветки. У них на сайте есть примеры https://support.typora.io/Code-Block-Styles/ но они несколько упрощенные и как добавить разметку с нуля не показывают ссылаясь на codemirror, а у меня знаний несколько не хватает  и примеров найти не могу.

**Comment by sikuda** [comment]
Посмотрел ничего не понял. Codemirror версии 5 имеет модули дополнения для разных языков и темы оформления для них типа codemirror-1C/theme/1c.css. 
Здесь же я кроме тем оформления ничего не нашел

**Comment by sikuda** [comment]
Закрываем.
